Fix post EAP-7.4.10.GA / RH-SSO-7.6.3.GA rebase CEKit error like:
'for a in self._descriptor.get("artifacts", [])
TypeError: 'NoneType' object is not iterable'

when iterating over list of artifacts in the sso/apply/patches module.

List of patches artifacts can't be empty. Either it needs to contain
valid artifacts, or shouldn't be present at all

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>